export const organisers = [
  {
    name: "Saurab Pandey",
    title: "Convenor",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Etesola Imchen",
    title: "Convenor",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "9897563546",
    email: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Aastha Singh",
    title: "Convenor and Technical Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Metmei",
    title: "Convenor",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Chiru Deepak",
    title: "Finance Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Divya Shikha",
    title: "Cultural Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Abhinav Kumar",
    title: "Cultural Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "7370032751",
    email: "abhinav3257@gmail.com",
    insta: "https://instagram.com/abhinav_02__",
  },
  {
    name: "Lungmei Simon",
    title: "Technical Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "PTSS Bhavana",
    title: "Sports Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Bendangmar",
    title: "Sports Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Akhilesh Kuriyal",
    title: "E-Sports Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Waluniba Jamir",
    title: "E-Sports Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Hari kumar",
    title: "Web Team and Coding Club",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Suraj Singh",
    title: "Web Team and Coding Club",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Britney",
    title: "Publicity Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Sai Nikhil",
    title: "Publicity Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Abhishek Raj",
    title: "Publicity Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Himanchal Warde",
    title: "Sponsorship Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Kenisede Nakro",
    title: "Sponsorship Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Imlitongzuk",
    title: "Hospitality Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Livitoli",
    title: "Hospitality Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Siddharth",
    title: "Photography",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Manyap",
    title: "Photography",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Anchal Rani",
    title: "Design Head",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
];
