export const organisers = [
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Srijan",
    image: "srijan.jpg",
    title: "Event - name",
    phone: "9897563546",
    fb: "https://www.facebook.com/srijan.iitrpr",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
];
