export const organisers = [
  {
    name: "Saurabh Pandey",
    title: "Convenor",
    image: "/organisers/pandey.webp",
    phone: "8252185444",
    email: "saurabhpandey134vs@gmail.com",
    insta: "https://instagram.com/___parle.g",
  },
  {
    name: "Etesola Imchen",
    title: "Convenor",
    image: "/organisers/ete.webp",
    phone: "9612461884",
    email: "etsolaimchen@gmail.com",
    insta: "https://instagram.com/eteso___imchen",
  },
  {
    name: "Aastha Singh",
    title: "Convenor",
    image: "/organisers/aastha.webp",
    phone: "8604637279",
    email: "aastha3219@nitnagaland.ac.in",
    insta: "https://instagram.com/aastha9x",
  },
  {
    name: "Metmei",
    title: "Convenor",
    image: "https://picsum.photos/130/130?image=1027",
    phone: "8252185444",
    email: "pandey@gmail.com",
    insta: "https://www.instagram.com/srijan.iitrpr/",
  },
  {
    name: "Abhinav Kumar",
    title: "Cultural Head",
    image: "/organisers/abhinav.webp",
    phone: "7370032751",
    email: "abhinav3257@gmail.com",
    insta: "https://www.instagram.com/abhinav_02__",
  },
  {
    name: "Shashank Chaturvedi",
    title: "Technical Head",
    image: "/organisers/shashank.webp",
    phone: "6388239819",
    email: "gshashank1998@gmail.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Sai Nikhil",
    title: "Publicity Head",
    image: "/organisers/nikhil.webp",
    phone: "7396315533",
    email: "sainikhilmaddiboina3@gmail.com",
    insta: "https://www.instagram.com/sai_nikhil_15",
  },
  {
    name: "PTSS Bhavana",
    title: "Sports Head",
    image: "/organisers/bhavana.webp",
    phone: "9492603899",
    email: "bhavanapurnaraju123@gmail.com",
    insta: "https://www.instagram.com/bhavana_bliss",
  },
  {
    name: "Hari kumar",
    title: "Web Team and Coding Club",
    image: "/organisers/hari.webp",
    phone: "7093357173",
    email: "hari70319@gmail.com",
    insta: "https://www.instagram.com/hasnaindaksh",
  },
  {
    name: "Suraj Singh",
    title: "Web Team and Coding Club",
    image: "/organisers/suraj.webp",
    phone: "8340479946",
    email: "ascyrax02@gmail.com",
    insta: "https://www.instagram.com/ascyrax",
  },
  {
    name: "Lungmei phom",
    title: "Technical Head",
    image: "/organisers/lungmei.webp",
    phone: "8787692466",
    email: "lungmeiphom1221@gmail.com",
    insta: "https://www.instagram.com/knight_sacrifice",
  },
  {
    name: "Deepak",
    title: "Finance Head",
    image: "/organisers/deepak.webp",
    phone: "7997623739",
    email: "chirudeepakkalepu@gmail.com",
    insta: "https://www.instagram.com/chiru_deepak_",
  },
  {
    name: "Britney Jidung",
    title: "Publicity Head",
    image: "/organisers/britney.webp",
    phone: "8575817649",
    email: "britneyjidung07@gmail.com",
    insta: "https://www.instagram.com/britney.jidung",
  },
  {
    name: "Himanchal Warde",
    title: "Sponsorship Team Lead",
    image: "/organisers/himanchal.webp",
    phone: "8850675648",
    email: "himanchalwarde007@gmail.com",
    insta: "https://www.instagram.com/himanchalwarde",
  },
  {
    name: "Halavath Siddhartha",
    title: "Photography",
    image: "/organisers/siddharth.webp",
    phone: "9652957295",
    email: "halavathsiddhartha@gmail.com",
    insta: "https://www.instagram.com/halavath_siddhartha",
  },
  {
    name: "Livitoli Shohe",
    title: "Hospitality Head",
    image: "/organisers/livitoli.webp",
    phone: "8787747494",
    email: "livitolishohe8@gmail.com",
    insta: "https://www.instagram.com/livitoli_shohe",
  },
  {
    name: "Anchal Rani",
    title: "Design Head",
    image: "/organisers/anchal.webp",
    phone: "7303368180",
    email: "ranianchal2001@gmail.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Manyap S Konyak",
    title: "Photography",
    image: "/organisers/manyap.webp",
    phone: "9366321130",
    email: "manyapskonyak@gmail.com",
    insta: "https://www.instagram.com/ayap_naga",
  },
];
