const DAY1 = "4th May";
const DAY2 = "5th May";

export const categories = [
  "Cultural",
  "Technical",
  "Esports",
  "Sports",
  "Mini Events",
];

export const eventCodes = {
  cultural: {
    "Cosplay - Solo": "CULT_CS",
    "Cosplay - Duo": "CULT_CD",
    "Cosplay - Trio": "CULT_CT",
    "Cosplay - Group": "CULT_CG",
    Ritzy: "CULT_RITZY",
    Rockville: "CULT_RV",
    "Voice of Ekarikthin": "CULT_VOE",
    "Dance - Solo": "CULT_DTGS",
    "Dance - Crew": "CULT_DTGC",
    "Dance Battle": "CULT_DB",
  },
  technical: {
    "Mud Race": "TEC_MR",
    "Pick N Place": "TEC_PNP",
    CodeCast: "TEC_CC",
    "Web Design": "TEC_WD",
    "Logo Designing": "TEC_LD",
    "CIVIL WITH CIVICUS": "TEC_CWC",
    Stockraze: "TEC_STK",
    Virgowords: "TEC_VIR",
    "Quiz Buzz": "TEC_QB",
  },
  esports: {
    COD: "ESP_COD",
    BGMI: "ESP_BGMI",
    CSGO: "ESP_CSGO",
    "DOTA 2": "ESP_DOTA",
    "Mobile legends": "ESP_ML",
  },
  sports: {
    "Table Tennis": "SPT_TT",
    Volleyball: "SPT_VOL",
    Rodies: "SPT_RDS",
    "Gully Cricket": "SPT_GC",
    Chess: "SPT_CH",
    Futsal: "SPT_FTSL",
    Badminton: "SPT_BD",
    "Mountain Biking": "SPT_MB",
  },
  "mini events": {
    "Treasure Hunt": "MNE_TH",
    "Wall Painting": "MNE_WP",
    "PIC Of the Day": "MNE_PIC",
    EDM: "MNE_EDM",
    "Rangoli Competition": "MNE_RG",
    Shipwreck: "MNE_SW",
    "Face Painting": "MNE_FP",
    "Short Film Contest": "MNE_SFC",
    "Arm Wrestling": "MNE_AW",
  },
};

export const eventCost = {
  CULT_CS: 400,
  CULT_CD: 700,
  CULT_CT: 1000,
  CULT_CG: 1300,
  CULT_RITZY: 500,
  CULT_RV: 2500,
  CULT_VOE: 300,
  CULT_DTGS: 200,
  CULT_DTGC: 800,
  CULT_DB: 300,
  TEC_MR: 0,
  TEC_PNP: 0,
  TEC_CC: 0,
  TEC_WD: 150,
  TEC_LD: 50,
  TEC_CWC: 100,
  TEC_STK: 100,
  TEC_VIR: 0,
  TEC_QB: 0,
  ESP_COD: 500,
  ESP_BGMI: 500,
  ESP_CSGO: 500,
  ESP_DOTA: 500,
  ESP_ML: 500,
  SPT_TT: 350,
  SPT_VOL: 600,
  SPT_RDS: 150,
  SPT_GC: 500,
  SPT_CH: 200,
  SPT_FTSL: 500,
  SPT_BD: 350,
  SPT_MB: 400,
  MNE_TH: 0,
  MNE_WP: 50,
  MNE_PIC: 0,
  MNE_EDM: 0,
  MNE_RG: 0,
  MNE_FP: 50,
  MNE_SW: 0,
  MNE_SFC: 200,
  MNE_AW: 100,
};

export const indEventCodes = Object.keys(eventCost);

const getEventCost = (category, event) =>
  eventCost[eventCodes[category.toLowerCase()][event]];

export const events = {
  cultural: [
    {
      event: "Cosplay - Solo",
      category: categories[0],
      price: getEventCost(categories[0], "Cosplay - Solo"),
      image: "/posters/cosplay.webp",
      description:
        "The face not tell the mood, but the costume will - Exceptional Service with unique fashion - Be someone's perfectly imperfect",
      date: DAY2,
      day: 2,
      time: "10:00 AM",
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Ritzy",
      category: categories[0],
      time: "10:00 AM",
      price: getEventCost(categories[0], "Ritzy"),
      image: "/posters/ritzy.webp",
      description: "Beauty is not flawless - It shines even through your flaws",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Dance - Solo",
      category: categories[0],
      price: getEventCost(categories[0], "Dance - Solo"),
      image: "/posters/dancetogroove.webp",
      description: "Keep the stage on FIRE",
      date: DAY1,
      day: 1,
      time: "10:00 AM",
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Rockville",
      category: categories[0],
      time: "10:00 AM",
      price: getEventCost(categories[0], "Rockville"),
      image: "/posters/rockville.webp",
      description: "Soul meets Music",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Cosplay - Duo",
      category: categories[0],
      price: getEventCost(categories[0], "Cosplay - Duo"),
      image: "/posters/cosplay.webp",
      description:
        "The face not tell the mood, but the costume will - Exceptional Service with unique fashion - Be someone's perfectly imperfect",
      date: DAY2,
      day: 2,
      time: "10:00 AM",
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Dance Battle",
      category: categories[0],
      time: "10:00 AM",
      price: getEventCost(categories[0], "Dance Battle"),
      image: "/posters/dancebattle.webp",
      description:
        "Dancing on street few years back might not be sounded like a great idea, but today is no less than a true dance form. Dance it out on the streets where audience will not only be your biggest supporters but also the judges. Participants can register for Solo, Duo and Group Dance battles",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Voice of Ekarikthin",
      category: categories[0],
      time: "10:00 AM",
      price: getEventCost(categories[0], "Voice of Ekarikthin"),
      image: "/posters/voe.webp",
      description:
        "When words fail, Music speaks. Showcase your talent through your voice on the stage of Ekarikthin. A platform for pitch perfect melodies and rhythm.",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Dance - Crew",
      category: categories[0],
      price: getEventCost(categories[0], "Dance - Crew"),
      image: "/posters/dancetogroove.webp",
      description: "Keep the stage on FIRE",
      date: DAY1,
      day: 1,
      time: "10:00 AM",
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Cosplay - Trio",
      category: categories[0],
      price: getEventCost(categories[0], "Cosplay - Trio"),
      image: "/posters/cosplay.webp",
      description:
        "The face not tell the mood, but the costume will - Exceptional Service with unique fashion - Be someone's perfectly imperfect",
      date: DAY2,
      day: 2,
      time: "10:00 AM",
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Cosplay - Group",
      category: categories[0],
      time: "10:00 AM",
      price: getEventCost(categories[0], "Cosplay - Group"),
      image: "/posters/cosplay.webp",
      description:
        "Cosplay which is the showcase of costumes of characters from different animes and films will showcase their acts and performances up on stage with a handsome price on the line",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
  ],
  technical: [
    {
      event: "Mud Race",
      category: categories[1],
      time: "10:00 AM",
      price: getEventCost(categories[1], "Mud Race"),
      image: "/posters/mudrace.webp",
      description: "Let's go Robo Racing",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "CodeCast",
      category: categories[1],
      time: "2:00 PM",
      price: getEventCost(categories[1], "CodeCast"),
      image: "/posters/codecast.webp",
      description:
        "Make it work, make it right, make it fast. CodeCast is a coding competition held on HackerRank. Registration for the contest starts from 25th April",
      date: DAY2,
      day: 2,
      venue: "Online",
    },
    {
      event: "Web Design",
      category: categories[1],
      time: "12:00 PM",
      price: getEventCost(categories[1], "Web Design"),
      image: "/posters/webdesign.webp",
      description:
        "Design the Template in HTML & CSS. We will provide you with a design template and you have to design your website according to the given template.",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Logo Designing",
      category: categories[1],
      time: "10:00 AM",
      price: getEventCost(categories[1], "Logo Designing"),
      image: "/posters/logodesign.webp",
      description: "The strongest logos tell simple stories",
      date: "1st & 2nd May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Pick N Place",
      category: categories[1],
      time: "10:00 AM",
      price: getEventCost(categories[1], "Pick N Place"),
      image: "/posters/picknplace.webp",
      description: "Push or Pick but Place",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "CIVIL WITH CIVICUS",
      category: categories[1],
      time: "10:00 AM",
      price: getEventCost(categories[1], "CIVIL WITH CIVICUS"),
      image: "/posters/civil.webp",
      description:
        "Presentation on Construction wastages and their Management with Urban and Rural development in Nagaland",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Stockraze",
      category: categories[1],
      time: "10:00 AM",
      price: getEventCost(categories[1], "Stockraze"),
      image: "/posters/stockraze.webp",
      description: "Show your trading skill without risking your real money",
      date: "4th & 5th May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Virgowords",
      category: categories[1],
      time: "10:00 AM",
      price: getEventCost(categories[1], "Virgowords"),
      image: "/posters/virgowords.webp",
      description:
        "To stimulate the awareness of technical & non-technical advancements an article writing competition will be conducted. The main objective of the article writing competition is to evaluate and to check the knowledge of candidates about specific topics and the way they describe the same in writing. Topic of Virgowords(Article Writing Competition) will be provided within the 5 disciplines namely Social Sciences, Culture, technical, economical and current advancement in industry",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Quiz Buzz",
      category: categories[1],
      time: "10:00 AM",
      price: getEventCost(categories[1], "Quiz Buzz"),
      image: "/posters/quizbuzz.webp",
      description:
        "Quiz Buzz is an event conducted as part of Ekarikthin 2022, NIT Nagaland. Ekarikthin is a techno-cultural fest of NIT Nagaland that is conducted annually. If you are a Science nerd - then show off your knowledge by participating in the Science and Technology quiz. Mind-boggling problems from a wide range of topics will be included. Put on your thinking caps and indulge yourself in these questions. This contest has two rounds Elimination and Final  . People who are selected in the elimination will go to the finals. It's an individual participation event. A wide range of questions is asked from Maths, Physics, Chemistry to Astronomy and Robotics",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
  ],
  esports: [
    {
      event: "COD",
      category: categories[2],
      time: "10:00 AM",
      price: getEventCost(categories[2], "COD"),
      image: "/posters/cod.webp",
      description: "Escape Actuality & Play Call Of Duty.",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "BGMI",
      category: categories[2],
      time: "10:00 AM",
      price: getEventCost(categories[2], "BGMI"),
      image: "/posters/bgmi.webp",
      description: "Just play your best, and forget the rest.",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "CSGO",
      category: categories[2],
      time: "10:00 AM",
      price: getEventCost(categories[2], "CSGO"),
      image: "/posters/csgo.webp",
      description: "REMOVE ANY DOUBTS IN YOUR HEAD- ITS US OR THEM!!",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "DOTA 2",
      category: categories[2],
      time: "10:00 AM",
      price: getEventCost(categories[2], "DOTA 2"),
      image: "/posters/dota.webp",
      description: "Play with the best to be the best!",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Mobile legends",
      category: categories[2],
      time: "10:00 AM",
      price: getEventCost(categories[2], "Mobile legends"),
      image: "/posters/mobilelegends.webp",
      description: "Nothing last forever, we can change the future (alucard)",
      date: "4th & 5th May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
  ],
  sports: [
    {
      event: "Badminton",
      category: categories[3],
      time: "10:00 AM",
      price: getEventCost(categories[3], "Badminton"),
      image: "/posters/badminton.webp",
      description: "BADMINTON",
      date: "4th & 5th May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Table Tennis",
      category: categories[3],
      time: "10:00 AM",
      price: getEventCost(categories[3], "Table Tennis"),
      image: "/posters/tabletennis.webp",
      description:
        "Leave your worries at the table - Don't tap it just smash it",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Volleyball",
      category: categories[3],
      time: "10:00 AM",
      price: getEventCost(categories[3], "Volleyball"),
      image: "/posters/volleyball.webp",
      description: "Join the club… And be part of volleyball history",
      date: "4th & 5th May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Rodies",
      category: categories[3],
      time: "10:00 AM",
      price: getEventCost(categories[3], "Rodies"),
      image: "/posters/rodies.webp",
      description:
        "In this event , a group of contestants travel to different destinations and participate in various tasks that challenge their physical, social and mental strength",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Mountain Biking",
      category: categories[3],
      time: "6:00 AM",
      price: getEventCost(categories[3], "Mountain Biking"),
      image: "/posters/mount.webp",
      description: "Ride a bike, feel the vibe",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Gully Cricket",
      category: categories[3],
      time: "10:00 AM",
      price: getEventCost(categories[3], "Gully Cricket"),
      image: "/posters/cricket.webp",
      description:
        "Never let it rest, until your good is better and your better is best. United we play, United we win!",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Chess",
      category: categories[3],
      time: "10:00 AM",
      price: getEventCost(categories[3], "Chess"),
      image: "/posters/chess.webp",
      description: "MOVE IN SILENCE ONLY SPEAK WHEN IT'S TIME TO SAY CHECKMATE",
      date: "4th & 5th May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Futsal",
      category: categories[3],
      time: "10:00 AM",
      price: getEventCost(categories[3], "Futsal"),
      image: "/posters/futsal.webp",
      description: "The game of the century",
      date: "4th & 5th May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
  ],
  "mini events": [
    {
      event: "Treasure Hunt",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "Treasure Hunt"),
      image: "/posters/treasure.webp",
      description: "YOUR TREASURE AWAITS YOU",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Wall Painting",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "Wall Painting"),
      image: "/posters/wallpainting.webp",
      description: "Show your Artistic skills",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "PIC Of the Day",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "PIC Of the Day"),
      image: "/posters/picoftheday.webp",
      description:
        "When words can't speak...Make your picture speak. so, what are you waiting for.. do register now and take part in the event!!",
      date: "4th & 5th May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "EDM",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "EDM"),
      image: "/posters/edm.webp",
      description:
        "EDM - Electronic Dance Music is a genre which is a combination of games, fun, big stages where people perform to screaming and excited crowd",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Rangoli Competition",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "Rangoli Competition"),
      image: "/posters/rangoli.webp",
      description: "Connect the right dots to make a perfect one",
      date: DAY2,
      day: 2,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Shipwreck",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "Shipwreck"),
      image: "/posters/shipwreck.webp",
      description:
        "Sink in the character, save yourself from the sinking ship!!",
      date: "1st May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Face Painting",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "Face Painting"),
      image: "/posters/facepainting.webp",
      description: "Let your face be the canvas!",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Short Film Contest",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "Short Film Contest"),
      image: "/posters/shortfilm.webp",
      description:
        "It's a Short film contest based on a theme 'Addiction Of social Media'. Where you should show us the impact of social media on this generation People. Film should be submitted on or before 1st May, 2022",
      date: "1st May",
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
    {
      event: "Arm Wrestling",
      category: categories[4],
      time: "10:00 AM",
      price: getEventCost(categories[4], "Arm Wrestling"),
      image: "/posters/arm.webp",
      description: "IF IT DOESN'TCHALLENGE YOU - IT DOESN'T CHANGE YOU.",
      date: DAY1,
      day: 1,
      venue: "Bamboo Clasroom - 2",
    },
  ],
};

const allEventsList = [];

for (let i = 0; i < categories.length; i++) {
  allEventsList.push(...events[categories[i].toLowerCase()]);
}

export const allEvents = allEventsList;
